swipe:
  3:
    left:
      command: exec i3 focus right
    right:
      command: exec i3 focus left
    up:
      command: exec i3 focus down
    down:
      command: exec i3 focus up
  4:
    left:
      command: exec swipe-workspace.sh next
      swipe: 1.5
    right:
      command: exec swipe-workspace.sh prev
      swipe: 1.5
    up:
      command: exec i3 fullscreen toggle
    down:
      command: exec i3 fullscreen toggle
pinch:
  in:
    sendkey: 'LEFTCTRL+MINUS'
  out:
    sendkey: 'LEFTCTRL+EQUAL'

threshold:
  swipe: 1.0
  pinch: 0.65

interval:
  swipe: 1.0
  pinch: 1.0
