#!/bin/bash
# ~/.config/bash/aliases

alias    l="eza       --group-directories-first --git"
alias   ls="eza -lah  --icons --group-directories-first --git"
alias   ll="eza -lah  --icons --group-directories-first --git"
alias   ld="eza -lahD --icons --group-directories-first --git"
alias tree="eza -aT   --icons --group-directories-first --git --git-ignore"

alias cat="bat"
alias vim="$HOME/.local/share/bob/nvim-bin/nvim"
