#!/bin/bash
# ~/.config/bash/aliases

alias    l="eza       --group-directories-first --git"
alias   ls="eza -lah  --icons --group-directories-first --git"
alias   ll="eza -lah  --icons --group-directories-first --git"
alias   ld="eza -lahD --icons --group-directories-first --git"
alias tree="eza -aT   --icons --group-directories-first --git --git-ignore"

alias cat="bat"
alias vim="$HOME/.local/share/bob/nvim-bin/nvim"

alias histfzf="history | fzf | cut -d ' ' -f 4- | xclip -selection clipboard"

alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gpu='git pull'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log'
alias glo='git log --graph --oneline --decorate'
